name: CMake

on:
  workflow_dispatch:
  
  push:
    tags:
      - "v*.*.*"
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build dependencies
      run: /bin/bash build-dependencies.sh

    - name: Build tgb-t
      run: /bin/bash build-main.sh
      
    - name: Test tgb-t
      run: /bin/bash build/tgb-t -v
            
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        tag_name: ${{ github.ref }}
        files: build/tgb-t
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
